services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: orleu.id.app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=postgres17;Database=orleu_id"
    ports:
      - "8081:80"
  
  db:
      image: postgres:17
      container_name: orleu.id.postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres17
        POSTGRES_DB: orleu_id
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./db:/docker-entrypoint-initdb.d
      ports:
        - "5435:5432"
volumes:
  pgdata:
