// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.cabinet.orleu.kz.Data;

#nullable disable

namespace server.cabinet.orleu.kz.Migrations
{
    [DbContext(typeof(CabinetDbContext))]
    partial class CabinetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refEmpdepartment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refEmpdepartment");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refEmpposition", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refEmpposition");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refKato", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refKato");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("empNationId")
                        .HasColumnType("integer");

                    b.Property<string>("nameKZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nameRU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pedNationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("refNationality");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdarea", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdarea");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdplace", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parentcode")
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdplace");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdposition", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdposition");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdqualcategory", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdqualcategory");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdschool", b =>
                {
                    b.Property<int>("schoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("schoolId"));

                    b.Property<string>("areacode")
                        .HasColumnType("text");

                    b.Property<string>("bin")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("localitycode")
                        .HasColumnType("text");

                    b.Property<string>("regioncode")
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("schoolId");

                    b.ToTable("refNobdschool");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdsciencedegree", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdsciencedegree");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refNobdsubject", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("kname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("refNobdsubject");
                });

            modelBuilder.Entity("server.cabinet.orleu.kz.Models.refOrleubranch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("bin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("namekz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nameru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refOrleubranch");
                });
#pragma warning restore 612, 618
        }
    }
}
